### ISSUE TITLE
windows?

### ISSUE THREAD

**Issue by AlexWhiteS** [SamuelTulach/NekoSwap#1]
Hello, what should I do to make this work on windows 11?
I'm looking at many data ptr drivers and can't figure out what has changed for this in windows 11

**Comment by SamuelTulach** [comment]
First of all, depending on your use case, it's going to be useless since most modern ACs check win32k pointers to be in range of win32kfull and win32kbase.

If you want to use it anyway then you will have to update the [pointer list](https://github.com/SamuelTulach/NekoSwap/blob/main/NekoSwap/NekoSwap/defines.h#L5) which is as simple as opening IDA and copying over the names which you will find under the given symbol name that is in the comment above each list.
